model:
  base_learning_rate: 1e-6
  target: specvqgan.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 128
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 848
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [53]
      dropout: 0.0

    lossconfig:
      target: specvqgan.modules.losses.vqperceptual.VQLPAPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 2001
        disc_weight: 0.8
        codebook_weight: 1.0
        min_adapt_weight: 1.0
        max_adapt_weight: 1.0
        perceptual_weight: 1.0

lightning:
  modelcheckpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        monitor: val/rec_loss_epoch
        mode: min
        # save_last: False
        save_top_k: 2
  callbacks:
    image_logger:
      target: train.ImageLogger
      params:
        for_specs: True
        vocoder_cfg:
          target: train.VocoderMelGan
          params:
            ckpt_vocoder: './vocoder/logs/vggsound/'
    # early_stop_callback:
    #   target: pytorch_lightning.callbacks.EarlyStopping
    #   params:
    #     monitor: val/rec_loss_epoch
    #     mode: min
    #     min_delta: 0.00
    #     patience: 10
    #     verbose: True
  trainer:
    sync_batchnorm: true
    lr_scheduler:
      target: torch.optim.lr_scheduler.ReduceLROnPlateau
      params:
        mode: 'min'
        factor: 0.1
        patience: 5
        threshold: 0.0001
        threshold_mode: 'rel'
        cooldown: 0
        min_lr: 0
        eps: 1e-08
        verbose: True
      monitor: 'val/rec_loss_epoch'

    

data:
  target: train.SpectrogramDataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8

    spec_dir_path: './data/dot1k/features/*/melspec_10s_22050hz'
    sample_rate: 22050
    mel_num: 80
    spec_len: 860
    spec_crop_len: 848
    random_crop: False

    train:
      target: specvqgan.data.dot1k.dot1kSpecsTrain
      params:
        specs_dataset_cfg:
          split_path: './data/dot1k_train.txt'
    validation:
      target: specvqgan.data.dot1k.dot1kSpecsValidation
      params:
        specs_dataset_cfg:
          split_path: './data/dot1k_valid.txt'
